on:
  push:
    tags:
      - v1.2
name: Continous Delivery Release apk
jobs:
  build:
    name: Build Apk
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
        - uses: actions/setup-java@v1
          - with:
              - swift-version: '5.7.0'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.3.9'
      - run: flutter pub get
      - run: flutter build apk -t lib/main.dart --split-per-abi
      - name: Release apk
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*.apk"
          token: ${{secrets.TOKEN}}


